### ISSUE TITLE
Uninstaller bug - unit name escaped

### ISSUE THREAD

**Issue by f3flight** [Jamesits/systemd-named-netns#11] opened 2018-08-11 16:59 UTC
```$ sudo make uninstall
systemctl stop netns@*.service || true
systemctl disable netns@*.service || true
Invalid unit name "netns@*.service" was escaped as "netns@\x2a.service" (maybe you should use systemd-escape?)
systemctl disable netns-tunnel@*.service || true
Invalid unit name "netns-tunnel@*.service" was escaped as "netns-tunnel@\x2a.service" (maybe you should use systemd-escape?)
Failed to disable unit: Unit file netns-tunnel@\x2a.service does not exist.
systemctl disable netns-bridge@*.service || true
Invalid unit name "netns-bridge@*.service" was escaped as "netns-bridge@\x2a.service" (maybe you should use systemd-escape?)
systemctl disable netns-nat@*.service || true
Invalid unit name "netns-nat@*.service" was escaped as "netns-nat@\x2a.service" (maybe you should use systemd-escape?)
rm -f //usr/lib/systemd/system/netns@.service
rm -f //usr/lib/systemd/system/netns-bridge@.service
rm -f //usr/lib/systemd/system/netns-nat@.service
rm -f //usr/lib/systemd/system/netns-tunnel@.service
rm -f /usr/bin/chnetns
rm -f /usr/sbin/netnsinit
```

**Comment by Jamesits** [comment] 2018-08-12 00:09
I'm unable to reproduce this from my devices. Could you please try out commit ce93f7b50ca7311c9f8ec1602df9fd4c059852b4 and see if it works?

**Comment by f3flight** [comment] 2018-08-12 04:50
Did not help but I've found a fix which works for me, plz check https://github.com/Jamesits/systemd-named-netns/pull/14

**Comment by Jamesits** [comment] 2018-08-12 12:23
I reproduced this issue on the same environment as you (Arch Linux, systemd 239), but cannot reproduce it on Ubuntu 18.04, systemd 234. I guess there are some behavior changes and I'll dig into that.

**Comment by Jamesits** [comment] 2018-08-12 13:32
[systemd-238.133-4](https://archive.archlinux.org/packages/s/systemd/systemd-238.133-4-x86_64.pkg.tar.xz): cannot reproduce -> https://github.com/systemd/systemd/commit/f58e62cbbc1c2842881a2a6ab9beda7bcb044a30
[systemd-239.0-2](https://archive.archlinux.org/packages/s/systemd/systemd-239.0-2-x86_64.pkg.tar.xz): can reproduce -> https://github.com/systemd/systemd/commit/de7436b02badc82200dc127ff190b8155769b8e7

**Comment by Jamesits** [comment] 2018-08-22 14:25
Before systemd 239 `systemctl disable "foo@*"` will return success but will not actually disable anything. On 239 it correctly reports an error which caused our uninstaller to fail. Your solution is correct, #14 have been merged.

**Closed as completed by Jamesits** 2018-08-22 14:25 UTC
